example: "Hello, world!"
char-1: ""
char-2: ""
char-3: ""
char-4: ""
char-5: ""
char-6: ""
char-7: ""
char-8: ""
char-9: ""
char-0: ""
ruby-bank-menu: "Ruby Exchange Menu"
ruby-itemsadder-namespacedid: "ores:ruby"
ruby-bank-size: 9